name: github_actions_1

on:
  push:
    branches: [github_actions]

jobs:
  greetings:
    runs-on: ubuntu-latest
  
    steps:
      - name: "Greetings"
        run: echo "Assalamwalaikum"
      - name: "Greetings in Urdu"
        run: echo "السلام علیکم"
